### ISSUE TITLE
Agent has stopped

### ISSUE THREAD

**Issue by pedroelisio** [brnunes/Android-SNMP#2]
Hi,
do you know, where to look to fix this problem?
Are you Portuguese?

![image](https://cloud.githubusercontent.com/assets/3877898/24007995/2ae9ad92-0a68-11e7-83a0-2d2349cf3ce4.png)

**Comment by bouaraour** [comment]
Hi ,

problem in java classes

no i'm algerienne

________________________________
De : Pedro Elísio Vieira da silva <notifications@github.com>
Envoyé : jeudi 16 mars 2017 16:48:37
À : brnunes/Android-SNMP
Cc : Subscribed
Objet : [brnunes/Android-SNMP] Agent has stopped (#2)


Hi,
do you know, where to look to fix this problem?
Are you Portuguese?

[image]<https://cloud.githubusercontent.com/assets/3877898/24007995/2ae9ad92-0a68-11e7-83a0-2d2349cf3ce4.png>

**Comment by pedroelisio** [comment]
Hi,
prob fix = I have to use a port >= 1024 or else the app fails on boot.
I'm going to use the lib as an SNMP agent with a remote SNMP Manager like "iReasoning MIB Browser".
Thanks,

**Comment by bouaraour** [comment]
https://www.facebook.com/profile.php?id=100005782968544

Youcef Bouaraour | Facebook<https://www.facebook.com/profile.php?id=100005782968544>
www.facebook.com
Youcef Bouaraour est sur Facebook. Inscrivez-vous sur Facebook pour communiquer avec Youcef Bouaraour et d’autres personnes que vous pouvez connaître....




________________________________
De : Pedro Elísio Vieira da silva <notifications@github.com>
Envoyé : lundi 20 mars 2017 16:02:13
À : brnunes/Android-SNMP
Cc : bouaraour; Comment
Objet : Re: [brnunes/Android-SNMP] Agent has stopped (#2)


Hi,
prob fix = I have to use a port >= 1024 or else the app fails on boot.
I'm going to use the lib as an SNMP agent with a remote SNMP Manager like "iReasoning MIB Browser".
Thanks,

**Comment by brnunes** [comment]
Hi @pedroelisio,
Yes, ports below 1024 can be opened only by root. Did that solve your problem?

**Comment by pedroelisio** [comment]
Yes, that solved the problem but I will use only the SNMP4J lib only for the agent part. The manager side I don't need it.
Pedro
